export default function (
    ctx: Context,
    _session: Session | null,
    opts: {
        questionnaire: any;
        action?: string;
        method?: "get" | "post";
        title?: string;
        submitLabel?: string;
        document?: boolean;
    },
) {
    const questionnaire = opts.questionnaire;
    if (!questionnaire || questionnaire.resourceType !== "Questionnaire") {
        return {
            ok: false as const,
            issues: [{
                code: "questionnaire.invalid",
                message: "A Questionnaire resource is required",
            }],
        };
    }

    const escape = (value: unknown) => ctx.fns.generator.escape({ value });
    const items = Array.isArray(questionnaire.item) ? questionnaire.item : [];
    const rendered = items.map((item: any) => ctx.fns.generator.renderItem({ item, depth: 1 }));
    const warnings = rendered.flatMap(result => result.warnings);
    const title = opts.title || questionnaire.title || questionnaire.name || questionnaire.id || "FHIR form";
    const canonical = questionnaire.url
        ? questionnaire.url + (questionnaire.version ? "|" + questionnaire.version : "")
        : questionnaire.id
            ? "Questionnaire/" + questionnaire.id
            : "Questionnaire/unknown";
    const method = opts.method ?? "post";
    const action = opts.action ?? "";
    const form = [
        "<!-- Generated by FHIR Forms scaffold. Safe to edit. -->",
        "<!-- Questionnaire: " + commentSafe(canonical) + " -->",
        '<form class="ff-form" method="' + method + '" action="' + escape(action) +
            '" data-questionnaire="' + escape(canonical) + '">',
        '  <header class="ff-header">',
        "    <h1>" + escape(title) + "</h1>",
        questionnaire.description ? "    <p>" + escape(questionnaire.description) + "</p>" : "",
        "  </header>",
        rendered.map(result => result.html).join("\n"),
        '  <footer class="ff-actions">',
        '    <button type="submit" name="__submit" value="1">' +
            escape(opts.submitLabel ?? "Submit") + "</button>",
        "  </footer>",
        "</form>",
    ].filter(Boolean).join("\n");

    if (opts.document === false) {
        return { ok: true as const, html: form, warnings };
    }

    const html = [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '  <meta charset="utf-8">',
        '  <meta name="viewport" content="width=device-width, initial-scale=1">',
        "  <title>" + escape(title) + "</title>",
        "  <style>",
        "    :root { color: #17201c; background: #f2efe6; font-family: Georgia, serif; }",
        "    * { box-sizing: border-box; }",
        "    body { margin: 0; padding: 2rem; }",
        "    .ff-form { max-width: 64rem; margin: auto; background: #fffdf8; border: 1px solid #c9c5b9; border-radius: 1rem; overflow: hidden; box-shadow: 0 1rem 3rem #17201c14; }",
        "    .ff-header, .ff-actions { padding: 1.25rem 1.5rem; }",
        "    .ff-header { border-bottom: 1px solid #d8d4c8; }",
        "    .ff-header h1 { margin: 0; font-size: clamp(1.6rem, 4vw, 2.6rem); }",
        "    .ff-header p { color: #59645e; margin-bottom: 0; }",
        "    .ff-field, .ff-group { display: grid; gap: .45rem; margin: 0; padding: 1rem 1.5rem; border: 0; border-bottom: 1px solid #e2ded3; }",
        "    .ff-group > legend { padding: 1.25rem 1.5rem .25rem; font-weight: 700; font-size: 1.2rem; }",
        "    .ff-field > span, .ff-field > label, .ff-field > legend { color: #505b55; font: 700 .72rem ui-monospace, monospace; letter-spacing: .08em; text-transform: uppercase; }",
        "    input, select, textarea { width: 100%; min-width: 0; padding: .65rem .75rem; border: 1px solid #b8b4a9; border-radius: .4rem; background: white; color: inherit; font: 1rem ui-sans-serif, sans-serif; }",
        "    textarea { min-height: 7rem; resize: vertical; }",
        "    input:focus, select:focus, textarea:focus { outline: 2px solid #147d70; outline-offset: 1px; }",
        "    .ff-options label { display: inline-flex; align-items: center; gap: .45rem; }",
        "    .ff-options input { width: auto; }",
        "    .ff-compound { display: grid; grid-template-columns: minmax(0, 1fr) max-content; gap: .5rem; }",
        "    .ff-compound select, .ff-compound input:last-child { width: auto; max-width: 15rem; }",
        "    .ff-unit { align-self: center; padding: 0 .75rem; white-space: nowrap; }",
        "    .ff-display { margin: 0; padding: 1rem 1.5rem; color: #59645e; border-bottom: 1px solid #e2ded3; }",
        "    .ff-actions { display: flex; justify-content: flex-end; }",
        "    button { border: 0; border-radius: .4rem; padding: .7rem 1rem; background: #126f64; color: white; font-weight: 700; cursor: pointer; }",
        "    button:hover { background: #0d584f; }",
        "    @media (max-width: 40rem) { body { padding: .75rem; } .ff-compound { grid-template-columns: 1fr; } .ff-compound select, .ff-compound input:last-child { width: 100%; max-width: none; } }",
        "  </style>",
        "</head>",
        "<body>",
        form,
        "</body>",
        "</html>",
    ].join("\n");

    return { ok: true as const, html, warnings };
}

function commentSafe(value: string): string {
    return value.replace(/--/g, "- -");
}
