// Auto-generated by ctx.genTypes — do not edit
// Injected<F> strips (ctx, session) — they are injected by the ctx.fns Proxy.
type Injected<F> = F extends (ctx: any, session: any, ...args: infer A) => infer R ? (...args: A) => R : never;

declare global {
    type Context = import("./$type_Context").Context;
    type Session = import("./$type_Session").Session;

    interface FnsRegistry {
        config: {
            coerce: Injected<typeof import("./config/coerce").default>;
            resolve: Injected<typeof import("./config/resolve").default>;
            validate: Injected<typeof import("./config/validate").default>;
        };
        dev: {
            build: Injected<typeof import("./dev/build").default>;
            def: Injected<typeof import("./dev/def").default>;
            lint: Injected<typeof import("./dev/lint").default>;
            manifest: Injected<typeof import("./dev/manifest").default>;
            sync: Injected<typeof import("./dev/sync").default>;
            test: Injected<typeof import("./dev/test").default>;
            typecheck: Injected<typeof import("./dev/typecheck").default>;
            watch: Injected<typeof import("./dev/watch").default>;
        };
        env: {
            fork: Injected<typeof import("./env/fork").default>;
            mode: Injected<typeof import("./env/mode").default>;
            pick: Injected<typeof import("./env/pick").default>;
        };
        events: {
            emit: Injected<typeof import("./events/emit").default>;
            join: Injected<typeof import("./events/join").default>;
            presence: Injected<typeof import("./events/presence").default>;
            reload: Injected<typeof import("./events/reload").default>;
            subscribe: Injected<typeof import("./events/subscribe").default>;
        };
        examples: {
            card: Injected<typeof import("./examples/card").default>;
            caseIds: Injected<typeof import("./examples/caseIds").default>;
            catalog: Injected<typeof import("./examples/catalog").default>;
            decisionSupport: Injected<typeof import("./examples/decisionSupport").default>;
            decisionSupportPanel: Injected<typeof import("./examples/decisionSupportPanel").default>;
            getCase: Injected<typeof import("./examples/getCase").default>;
            orderCatalog: Injected<typeof import("./examples/orderCatalog").default>;
            orderFields: Injected<typeof import("./examples/orderFields").default>;
            orderSearch: Injected<typeof import("./examples/orderSearch").default>;
            render: Injected<typeof import("./examples/render").default>;
            result: Injected<typeof import("./examples/result").default>;
            cases: {
                adaptiveIntake: Injected<typeof import("./examples/cases/adaptiveIntake").default>;
                attachment: Injected<typeof import("./examples/cases/attachment").default>;
                basic: Injected<typeof import("./examples/cases/basic").default>;
                bodyMap: Injected<typeof import("./examples/cases/bodyMap").default>;
                cardinality: Injected<typeof import("./examples/cases/cardinality").default>;
                codingSugar: Injected<typeof import("./examples/cases/codingSugar").default>;
                conflictingCoding: Injected<typeof import("./examples/cases/conflictingCoding").default>;
                decisionSupport: Injected<typeof import("./examples/cases/decisionSupport").default>;
                diagnosis: Injected<typeof import("./examples/cases/diagnosis").default>;
                duplicates: Injected<typeof import("./examples/cases/duplicates").default>;
                encoded: Injected<typeof import("./examples/cases/encoded").default>;
                invalidValues: Injected<typeof import("./examples/cases/invalidValues").default>;
                malformedPath: Injected<typeof import("./examples/cases/malformedPath").default>;
                medicationSentence: Injected<typeof import("./examples/cases/medicationSentence").default>;
                openChoice: Injected<typeof import("./examples/cases/openChoice").default>;
                orderComposer: Injected<typeof import("./examples/cases/orderComposer").default>;
                references: Injected<typeof import("./examples/cases/references").default>;
                sparse: Injected<typeof import("./examples/cases/sparse").default>;
                symptoms: Injected<typeof import("./examples/cases/symptoms").default>;
                visits: Injected<typeof import("./examples/cases/visits").default>;
                vitals: Injected<typeof import("./examples/cases/vitals").default>;
                wrongParent: Injected<typeof import("./examples/cases/wrongParent").default>;
            };
            ui: {
                coding: Injected<typeof import("./examples/ui/coding").default>;
                form: Injected<typeof import("./examples/ui/form").default>;
                group: Injected<typeof import("./examples/ui/group").default>;
                input: Injected<typeof import("./examples/ui/input").default>;
                quantity: Injected<typeof import("./examples/ui/quantity").default>;
                questionnaire: Injected<typeof import("./examples/ui/questionnaire").default>;
                repeat: Injected<typeof import("./examples/ui/repeat").default>;
                select: Injected<typeof import("./examples/ui/select").default>;
                styles: Injected<typeof import("./examples/ui/styles").default>;
            };
        };
        generator: {
            escape: Injected<typeof import("./generator/escape").default>;
            generate: Injected<typeof import("./generator/generate").default>;
            path: Injected<typeof import("./generator/path").default>;
            renderItem: Injected<typeof import("./generator/renderItem").default>;
            write: Injected<typeof import("./generator/write").default>;
        };
        http: {
            dispatch: Injected<typeof import("./http/dispatch").default>;
            loadRoutes: Injected<typeof import("./http/loadRoutes").default>;
            match: Injected<typeof import("./http/match").default>;
            middleware: Injected<typeof import("./http/middleware").default>;
            toResponse: Injected<typeof import("./http/toResponse").default>;
        };
        lifecycle: {
            order: Injected<typeof import("./lifecycle/order").default>;
            start: Injected<typeof import("./lifecycle/start").default>;
            stop: Injected<typeof import("./lifecycle/stop").default>;
        };
        log: {
            debug: Injected<typeof import("./log/debug").default>;
            emit: Injected<typeof import("./log/emit").default>;
            error: Injected<typeof import("./log/error").default>;
            info: Injected<typeof import("./log/info").default>;
            level: Injected<typeof import("./log/level").default>;
            warn: Injected<typeof import("./log/warn").default>;
        };
        parser: {
            materialize: Injected<typeof import("./parser/materialize").default>;
            parse: Injected<typeof import("./parser/parse").default>;
            parseAnswer: Injected<typeof import("./parser/parseAnswer").default>;
            resolve: Injected<typeof import("./parser/resolve").default>;
            tokenize: Injected<typeof import("./parser/tokenize").default>;
        };
        project: {
            classify: Injected<typeof import("./project/classify").default>;
            pluginPaths: Injected<typeof import("./project/pluginPaths").default>;
            projectRoot: Injected<typeof import("./project/projectRoot").default>;
            roots: Injected<typeof import("./project/roots").default>;
            scan: Injected<typeof import("./project/scan").default>;
            workdir: Injected<typeof import("./project/workdir").default>;
        };
        repl: {
            eval: Injected<typeof import("./repl/eval").default>;
            load: Injected<typeof import("./repl/load").default>;
            secret: Injected<typeof import("./repl/secret").default>;
        };
        spec: {
            render: Injected<typeof import("./spec/render").default>;
        };
        tailwind: {
            build: Injected<typeof import("./tailwind/build").default>;
        };
        ui: {
            attr: Injected<typeof import("./ui/attr").default>;
            badge: Injected<typeof import("./ui/badge").default>;
            box: Injected<typeof import("./ui/box").default>;
            button: Injected<typeof import("./ui/button").default>;
            field: Injected<typeof import("./ui/field").default>;
            form: Injected<typeof import("./ui/form").default>;
            highlight: Injected<typeof import("./ui/highlight").default>;
            notice: Injected<typeof import("./ui/notice").default>;
            page: Injected<typeof import("./ui/page").default>;
            row: Injected<typeof import("./ui/row").default>;
            tabs: Injected<typeof import("./ui/tabs").default>;
        };
    }

    interface RootFns {
    genTypes: Injected<typeof import("./genTypes").default>;
    layout: Injected<typeof import("./$layout").default>;
    loadFns: Injected<typeof import("./loadFns").default>;
    }

    namespace types {
        namespace log {
            type LogRecord = import("./log/$type_LogRecord").LogRecord;
        }
    }

    interface CtxState {
        appRoots: import("./project/$state_appRoots").appRoots;
        presence: import("./events/$state_presence").presence;
        replSecret: import("./repl/$state_replSecret").replSecret;
    }
}
export {};
